= Manage TLS

[abstract]
To support secure communications between nodes, clusters, and clients, Couchbase Server provides interfaces for the configuration of on-the-wire security settings.

[#tls-and-cipher-suites]
== TLS and Cipher-Suites

_Transport Layer Security_ (TLS) is a protocol that provides security over a computer network.
Couchbase Server supports the configuration of TLS, to secure communications between cluster-nodes, clusters, and external clients: this includes selection of an appropriate TLS version.

TLS supports multiple methods for exchanging keys, encrypting data, and authenticating message-integrity.
Appropriate methods, supported by both participants in an intended networked communication, can be specified through selection of an appropriate _cipher-suite_, from defined lists of ones acceptable.
Couchbase Server also allows a _customized_ list to be defined and used &#8212; either globally or _per service_.

When a TLS connection is established between a client application and Couchbase Server &#8212; for example, using the secure port `18091` &#8212; a _handshake_ occurs, as defined by the https://en.wikipedia.org/wiki/Transport_Layer_Security#TLS_handshake[TLS Handshake Protocol].
As part of this exchange, the client sends to the server the client's own cipher-suite list; which specifies the cipher-suites that the client itself supports.
Server-settings are provided to specify whether the server then conforms &#8212; either globally or _per service_ &#8212; to its own or the client's preference, in selecting a commonly acceptable cipher-suite to be used for the communication.

Once the selection has been made by Couchbase Server, Couchbase Server notifies the client of the selection, and the handshake process continues.

=== On-the-Wire Security Settings: Global and Per Service

Security parameters are provided that allow on-the-wire security to be configured for all Couchbase Services.
The services are `data` (Data Service), `fullTextSearch` (Search Service), `index` (Index Service), `eventing` (Eventing Service), `query` (Query Service), `analytics` (Analytics Service), and `backup` (Backup Service).

Also treated as a service, in the context of on-the-wire security settings, is the Couchbase-Server _Cluster Manager_ (referred to as `clusterManager`).

When a cluster is first created, since no custom settings exist either globally or per service, cluster-wide defaults are used for all settings: these are described in xref:manage:manage-security/manage-tls.adoc#security-settings[Security Settings], below.
Subsequently, if any custom setting is created globally, and an equivalent custom setting has _not_ been made for one or more services, those services use the global setting.
When a custom setting is made for a service, that setting is duly used by the service; and any equivalent global setting is ignored by the service.

[#security-settings]
==== On-the-Wire Security Settings

Three configurable, on-the-wire security settings are provided both globally and per service.
Additionally, one non-configurable setting is provided per service.
These are as follows:

* *tlsMinVersion*.
Specifies the minimum accepted TLS version.
The value can be `tlsv1` (the default), `tlsv1.1`, `tlsv1.2`, or `tlsv1.3`.
+
This parameter can be established both globally and per service.
However, a value of `tlsv1.3` can be established only for the following services: `data`, `fullTextSearch`, `index`, `eventing`, `query`, `analytics`, and `backup`.

* *honorCipherOrder*.
Specifies whether the service uses its own cipher-suite preference, rather than the client's.
The default value of `honorCipherOrder` is `true`: a setting of `false` is _not_ recommended, since insecure.

* *cipherSuites*.
Specifies a list of the cipher suites to be used by the service, in order of preference.
The argument must be a list of cipher suites, each of which is listed as an element in the array that is the _read-only_ value of the non-configurable *supportedCipherSuites* setting.
+
If, for any service, no value is provided for the *cipherSuites* parameter, the service defaults to using the custom list that has been configured globally.
If no global list has been configured, the service defaults to using the cipher-suite list provided as a general default by the operating system (which can, on Linux, be retrieved with the `openssl ciphers -v` command).

* *supportedCipherSuites*.
An array whose members are the cipher-suites for the service.
The array is for informational purposes, and is _read-only_.

In addition to those listed above, several additional on-the-wire parameters are provided, these being _global-only_.
For details, see the CLI reference page for xref:cli:cbcli/couchbase-cli-setting-security.adoc[setting-security]; and the REST reference page xref:rest-api:rest-setting-security.adoc[On-the-Wire Security API].

[#manage-on-the-wire-security-with-the-cli]
== Manage On-the-Wire Security Globally, with the CLI

The Couchbase CLI allows _cluster-wide_ on-the-wire security-setting to be retrieved; and allows the _global_ settings to be modified.

[#get-the-cluster-wide-security-configuration-with-the-cli]
=== Get the Cluster-Wide Security Configuration, with the CLI

The _cluster-wide_ security configuration includes both _global_ and _per service_ settings.
The current configuration can be retrieved with the xref:cli:cbcli/couchbase-cli-setting-security.adoc[setting-security] command.
This is shown by the following example.
Note that the output is piped to the https://stedolan.github.io/jq[jq^] command, to optimise the output's readability:

----
/opt/couchbase/bin/couchbase-cli setting-security \
-c 10.144.210.101:8091 \
-u Administrator \
-p password \
--get | jq '.'
----

If successful, the command returns output such as the following:

----
{
  "disableUIOverHttp": false,
  "disableUIOverHttps": false,
  "disableWWWAuthenticate": false,
  "tlsMinVersion": "tlsv1",
  "cipherSuites": [],
  "honorCipherOrder": true,
  "data": {
    "supportedCipherSuites": [
      "TLS_AES_256_GCM_SHA384",
      "TLS_CHACHA20_POLY1305_SHA256",
            .
            .
      "TLS_PSK_WITH_CAMELLIA_128_CBC_SHA256"
    ]
  },
  "fullTextSearch": {
    "supportedCipherSuites": [
      "TLS_RSA_WITH_RC4_128_SHA",
      "TLS_RSA_WITH_3DES_EDE_CBC_SHA",
            .
            .
      "TLS_CHACHA20_POLY1305_SHA256"
    ]
  },
  "index": {
    "supportedCipherSuites": [
      "TLS_RSA_WITH_RC4_128_SHA",
      "TLS_RSA_WITH_3DES_EDE_CBC_SHA",
            .
            .
      "TLS_CHACHA20_POLY1305_SHA256"
    ]
  },
  "eventing": {
    "supportedCipherSuites": [
      "TLS_RSA_WITH_RC4_128_SHA",
      "TLS_RSA_WITH_3DES_EDE_CBC_SHA",
            .
            .
      "TLS_CHACHA20_POLY1305_SHA256"
    ]
  },
  "query": {
    "supportedCipherSuites": [
      "TLS_RSA_WITH_RC4_128_SHA",
      "TLS_RSA_WITH_3DES_EDE_CBC_SHA",
            .
            .
      "TLS_CHACHA20_POLY1305_SHA256"
    ]
  },
  "analytics": {
    "supportedCipherSuites": [
      "TLS_AES_128_GCM_SHA256",
      "TLS_AES_256_GCM_SHA384",
            .
            .
      "TLS_EMPTY_RENEGOTIATION_INFO_SCSV"
    ]
  },
  "backup": {
    "supportedCipherSuites": [
      "TLS_RSA_WITH_RC4_128_SHA",
      "TLS_RSA_WITH_3DES_EDE_CBC_SHA",
      "TLS_RSA_WITH_AES_128_CBC_SHA",
              .
              .
      "TLS_CHACHA20_POLY1305_SHA256"
    ]
  },
  "clusterManager": {
    "supportedCipherSuites": [
      "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
      "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
              .
              .
      "TLS_RSA_WITH_3DES_EDE_CBC_SHA"
    ]
  }
}
----

The returned object contains attribute-value pairs that represent the current cluster-wide on-the-wire security configuration.

For information on the first three attributes shown in this example &#8212;   `disableUIOverHttp`, `disableUIOverHttps`, and `disableWWWAuthenticate` &#8212; see the CLI reference page for xref:cli:cbcli/couchbase-cli-setting-security.adoc[setting-security]; and the REST reference page xref:rest-api:rest-setting-security.adoc[On-the-Wire Security API].

The `tlsMinVersion` is shown as set to the default value, which is `tlsv1`.
Likewise, the value of `honorCipherOrder` is the default, which is `true`.

No custom cipher-suite list has been provided as the value of `cipherSuites`: accordingly, the array is empty.
This means that the cluster uses the global default cipher-suite list, which is provided by the operating system.

The remaining attributes in the object correspond to the services for which on-the-wire security can be configured: `data`, `fullTextSearch`, `index`, `eventing`, `query`, `analytics`, `backup`, and `clusterManager`.
Currently, each contains a single attribute-value pair, specifying `supportedCipherSuites`.
The value of the list, in each case, is a _read-only_ list of cipher-suites (truncated, in the output-display provided above), which is informational purposes: if a cipher-suite list is to be custom-configured for the service, it must only feature cipher-suites included in the list that is value of `supportedCipherSuites`.

[#set-the-global-security-configuration-with-the-cli]
=== Set the Global Security Configuration, with the CLI

The Couchbase CLI allows the cluster's _global_ on-the-wire security-setting to be established.
For example:

----
/opt/couchbase/bin/couchbase-cli setting-security \
-c 10.144.210.101:8091 \
-u Administrator \
-p password \
--set \
--tls-min-version tlsv1.2 \
--tls-honor-cipher-order 1 \
--cipher-suites TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA
----

The `set` parameter establishes use of the command to make settings.
The `tls-honor-cipher-order` parameter-value is specified as 1, meaning that the server’s preference-order for cipher-suites will be used, rather than the client’s.
Note, however, that this setting is also the default; and so will remain established even if this parameter is not specified.
The `cipher-suites` parameter takes a value that is a list of cipher-suites to be used for the cluster.
Note that if the value for cipherSuites is an empty list (`""`), this specifies that the Couchbase Server default cipher-suite list is to be used.

If the call is successful, the following is displayed:

----
SUCCESS: Security settings updated
----

The new settings can be retrieved by means, again, of the `setting-security` command with the `get` parameter.
The initial part of the output is now as follows:

----
{
  "disableUIOverHttp": false,
  "disableUIOverHttps": false,
  "disableWWWAuthenticate": false,
  "tlsMinVersion": "tlsv1.2",
  "cipherSuites": [
    "TLS_RSA_WITH_AES_128_CBC_SHA",
    "TLS_RSA_WITH_AES_256_CBC_SHA"
  ],
  "honorCipherOrder": true,
----

The specified cipher-suite list has now become the global setting; while the TLS minimum version for the cluster has been set to 1.2.
These are now the settings for all services that do not have their own settings.

See xref:cli:cbcli/couchbase-cli-setting-security.adoc[setting-security], for information on additional parameters.

[#manage-ciphers-with-the-rest-api]
== Manage On-the-Wire Security Globally, with the REST API

To manage on-the-wire security settings globally, with the REST API, use the `GET` and `POST` methods with the `/settings/security` URI.

[#get-the-cluster-wide-security-settings-with-the-rest-api]
=== Get the Cluster-Wide Security Settings, with the REST API

The following example retrieves cluster-wide on-the-wire security-settings:

----
curl  -u Administrator:password -v -X GET \
http://10.144.210.101:8091/settings/security | jq '.'
----

If successful, the call returns the following object:

----
{
  "disableUIOverHttp": false,
  "disableUIOverHttps": false,
  "disableWWWAuthenticate": false,
  "tlsMinVersion": "tlsv1.2",
  "cipherSuites": [
    "TLS_RSA_WITH_AES_128_CBC_SHA",
    "TLS_RSA_WITH_AES_256_CBC_SHA"
  ],
  "honorCipherOrder": true,
  "data": {
    "supportedCipherSuites": [
      "TLS_AES_256_GCM_SHA384",
              .
              .
              .
----

For details of the returned parameters, see xref:manage:manage-security/manage-tls.adoc#get-the-cluster-wide-security-configuration-with-the-cli[Get the Cluster-Wide Security Configuration, with the CLI], above.

[#set-the-global-security-configuration-with-the-rest-api]
=== Set the Global Security Configuration, with the REST API

To set the global on-the-wire security configuration with the REST API, enter an expression such as the following:

----
curl  -u Administrator:password -v -X POST \
http://10.144.210.101:8091/settings/security \
-d honorCipherOrder=true \
-d 'cipherSuites=["TLS_RSA_WITH_AES_128_CBC_SHA", "TLS_RSA_WITH_AES_256_CBC_SHA"]'
----

The `honorCipherOrder` flag is specified as `true`, meaning that the server's order of preference for cipher-suites, rather than the client's, will be used.
(Note, however, that `true` is the default; meaning that the server's preference is used even if this parameter is not specified.)
The value specified for the `cipherSuites` flag is a list of cipher-suites that can be used for the server, in order of preference.
If the value for `cipherSuites` is an empty list (`[]`), this specifies that the Couchbase Server default cipher-suite list is to be used.

If successful, the call gives `200 OK`, and returns an empty array.

For more information, see the REST API reference page xref:rest-api:rest-setting-security.adoc[On-the-Wire Security API].

[#manage-on-the-wire-security-per-service-with-the-rest-api]
== Manage On-the-Wire Security Per Service, with the REST API

Couchbase Server allows on-the-wire security to be configured _per service_; by means of the `GET` and `POST` methods, and the `/settings/security/<service-name>` URI.

[#get-per-service-security-settings-with-the-rest-api]
=== Get Per Service Security Settings, with the REST API

The following expression uses the `GET` method with the `/settings/security/<service-name>` URI, to retrieve the current on-the-wire security settings for the Data Service.
The value of the `<service-name>` path-parameter is thus specified as `data`:

----
curl  -u Administrator:password -v -X GET \
http://10.144.210.101:8091/settings/security/data | jq '.'
----

If successful, the call returns an object such as the following:

----
{
  "supportedCipherSuites": [
    "TLS_AES_256_GCM_SHA384",
    "TLS_CHACHA20_POLY1305_SHA256",
    "TLS_AES_128_GCM_SHA256",
    "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
    "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
    "TLS_DHE_DSS_WITH_AES_256_GCM_SHA384",
    "TLS_DHE_RSA_WITH_AES_256_GCM_SHA384",
    "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256",
                .
                .
                .
----

This object (here displayed in truncated form) consists only of the read-only `supportedCipherSuites` parameter.
This indicates that no other custom settings have yet been made for the Data Service.
The Data Service is therefore currently defaulting to whatever settings have been established globally.

[#set-per-service-security-settings-with-the-rest-api]
=== Set Per Service Security Settings, with the REST API

The following expression uses the `POST` method with the `/settings/security/<service-name>` URI, to establish a cipher-suite list for the Data Service.

----
curl -u Administrator:password -v -X POST \
http://10.144.210.101:8091/settings/security/data \
-d 'cipherSuites=["TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384", "TLS_DHE_DSS_WITH_AES_256_GCM_SHA384","TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256"]'
----

If successful, the call returns `200 OK` and an empty array.
The results can now be checked, by (again) using the `GET` method with the `/settings/security/data` URI:

----
{
  "cipherSuites": [
    "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
    "TLS_DHE_DSS_WITH_AES_256_GCM_SHA384",
    "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256"
  ],
  "supportedCipherSuites": [
    "TLS_AES_256_GCM_SHA384",
    "TLS_CHACHA20_POLY1305_SHA256",
    "TLS_AES_128_GCM_SHA256",
    "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
    "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
                .
                .
                .
----

The returned object (shown here in truncated form) indicates that the cipher-suite list specified in the `POST` has duly been made the list for the Data Service.

For more information, see xref:rest-api:rest-setting-security.adoc[On-the-Wire Security API].

[#alternative-cipher-suite-list-configuration]
== Alternative Global Cipher-Suite List-Configuration

The recommended ways of establishing a cipher-suite list globally are given above, for the xref:manage:manage-security/manage-tls.adoc#set-the-global-security-configuration-with-the-cli[CLI] and the xref:manage:manage-security/manage-tls.adoc#set-the-global-security-configuration-with-the-rest-api[REST API].
However, the list can also be created by setting the `COUCHBASE_SSL_CIPHER_LIST` environment variable: this _legacy_ means of establishing a custom cipher-suite is only supported on _Linux_ operating systems, only applies to the Data Service, and requires that the variable be defined _before_ Couchbase Server is started.

The environment variable can be set in either of the following ways:

* Specify an explicit list of ciphers to be used.
For example:
+
----
COUCHBASE_SSL_CIPHER_LIST="DHE-DSS-AES128-SHA,CAMELLIA128-SHA"
----

* Specify ciphers by security-level.
For example, to specify that all ciphers in both _medium_ and _high_ categories
be used, enter the following:
+
----
COUCHBASE_SSL_CIPHER_LIST="MEDIUM,HIGH"
----

To display the ciphers available on your Linux platform for a particular security level, use the `openssl` command.
For example, to display the _high_-level ciphers, enter the following:

----
openssl ciphers -v 'HIGH'
----

To check the current value of the `COUCHBASE_SSL_CIPHER_LIST` environment variable, type `printenv` at the Linux prompt: this returns a list of all currently set environment variables.
