= Role-Based Access Control (RBAC)
:page-aliases: rest-bucket-auth,rest-user-create,rest-user-getname,rest-user-password-put,rest-user-delete

[abstract]
Full  and Security Administrators can manage the Couchbase _Role-Based Access Control_ (RBAC) system, using the REST API.

[#description]
== Description

A Couchbase-Server _role_ permits one or more _resources_ to be accessed according to defined _privileges_.
Roles can be assigned to individual users, and to groups, by means of the REST API.

For a complete list of roles, see xref:learn:security/roles.adoc[Roles].
Note that most roles can be assigned only on the _Enterprise Edition_ of Couchbase Server: on the _Community Edition_ of Couchbase Server, only the `bucket_full_access`,
`admin`, and `ro_admin` roles can be assigned.

For more information, see xref:learn:security/authorization-overview.adoc[Authorization].

[#get-information-on-users-and-groups]
== Retrieve Information on Roles, Users, and Groups

The REST API allows information to be retrieved on available roles; and on the cluster's currently defined users and groups.
Curl syntax, parameter-descriptions, examples, and call-specific responses are described in the subsections below.
See xref:rest-api:rbac.adoc[General Responses], for further descriptions of error notifications.

=== List Roles

To list roles, use the `GET` method with the `/settings/rbac/roles` URI.
The curl syntax is as follows:

----
curl -X GET -u <username:password>
  http://<ip-address-or-domain-name>:8091/settings/rbac/roles
----

If successful, this returns `200 OK`, and an array that contains a description of every available role.

==== Example: List Roles

The following example lists the roles for the current cluster.
Note that in this example (as in others, below) the output is piped to the https://stedolan.github.io/jq/[jq] command, to facilitate readability.

----
curl -v -X GET http://10.143.201.101:8091/settings/rbac/roles \
-u Administrator:password | jq
----

If successful, the call returns an array, containing information on every role:

----
[
  {
    "role": "admin",
    "name": "Full Admin",
    "desc": "Can manage all cluster features (including security). This user can access the web console. This user can read and write all data.",
    "ce": true
  },
  {
    "role": "ro_admin",
    "name": "Read-Only Admin",
    "desc": "Can view all cluster statistics. This user can access the web console. This user can read some data.",
    "ce": true
  },
  {
    "role": "security_admin",
    "name": "Security Admin",
    "desc": "Can view all cluster statistics and manage user roles, but not grant Full Admin or Security Admin roles to other users or alter their own role. This user can access the web console. This user cannot read data."
  },
            .
            .
----

[#list-current-users-and-their-roles]
=== List Current Users and Their Roles

To list current users, use the `GET` method with the `/settings/rbac/users` URI.
The curl syntax is as follows:

----
curl -X GET <ip-address-or-domain-name>:8091/settings/rbac/users
  -u <username:password>
----

This returns an array, each of whose members is an object containing information on a currently defined user.

[#example-list-current-users]
==== Example: List Current Users

The following example lists the users currently defined on the cluster:

----
curl -v -X GET http://10.143.201.101:8091/settings/rbac/users \
-u Administrator:password | jq
----

If successful, the call returns `200 OK`, and an array such as the following:

----
[
  {
    "id": "testUser",
    "domain": "local",
    "roles": [
      {
        "role": "ro_admin",
        "origins": [
          {
            "type": "user"
          }
        ]
      }
    ],
    "groups": [],
    "external_groups": [],
    "name": "",
    "password_change_date": "2020-08-11T03:48:18.000Z"
  }
]
----

In this example, the object that is the sole member of the array contains values that specify the `domain`, the `role(s)`, the `groups`, the `external_groups`, the `name`, and the last `password_change_date` for a user who is currently the only one defined. 
