= Role-Based Access Control (RBAC)
:page-aliases: rest-bucket-auth,rest-user-create,rest-user-getname,rest-user-password-put,rest-user-delete

[abstract]
Full  and Security Administrators can manage the Couchbase _Role-Based Access Control_ (RBAC) system, using the REST API.

[#description]
== Description

A Couchbase-Server _role_ permits one or more _resources_ to be accessed according to defined _privileges_.
Roles can be assigned to individual users, and to groups, by means of the REST API.

For a complete list of roles, see xref:learn:security/roles.adoc[Roles].
Note that most roles can be assigned only on the _Enterprise Edition_ of Couchbase Server: on the _Community Edition_ of Couchbase Server, only the `bucket_full_access`,
`admin`, and `ro_admin` roles can be assigned.

For more information, see xref:learn:security/authorization-overview.adoc[Authorization].

[#get-information-on-users-and-groups]
== Retrieve Information on Roles, Permissions, Users, and Groups

The REST API allows information to be retrieved on available roles and permissions; and on the cluster's currently defined users and groups.
Curl syntax, parameter-descriptions, examples, and call-specific responses are described in the subsections below.
See xref:rest-api:rbac.adoc[General Responses], for further descriptions of error notifications.

=== List Roles

To list roles, use the `GET` method with the `/settings/rbac/roles` URI.
The curl syntax is as follows:

----
curl -X GET http://<ip-address-or-domain-name>:8091/settings/rbac/roles
  -u <username:password>
----

If successful, this returns `200 OK`, and an array that contains a description of every available role.

==== Example: List Roles

The following example lists the roles for the current cluster.
Note that in this example (as in others, below) the output is piped to the https://stedolan.github.io/jq/[jq] command, to facilitate readability.

----
curl -v -X GET http://10.143.201.101:8091/settings/rbac/roles \
-u Administrator:password | jq
----

If successful, the call returns an array, containing information on every role:

----
[
  {
    "role": "admin",
    "name": "Full Admin",
    "desc": "Can manage all cluster features (including security). This user can access the web console. This user can read and write all data.",
    "ce": true
  },
  {
    "role": "ro_admin",
    "name": "Read-Only Admin",
    "desc": "Can view all cluster statistics. This user can access the web console. This user can read some data.",
    "ce": true
  },
  {
    "role": "security_admin",
    "name": "Security Admin",
    "desc": "Can view all cluster statistics and manage user roles, but not grant Full Admin or Security Admin roles to other users or alter their own role. This user can access the web console. This user cannot read data."
  },
            .
            .
----

[#list-current-users-and-their-roles]
=== List Current Users and Their Roles

To list current users, use the `GET` method with the `/settings/rbac/users` URI.
The curl syntax is as follows:

----
curl -X GET http://<ip-address-or-domain-name>:8091/settings/rbac/users
  -u <username:password>
----

This returns an array, each of whose members is an object containing information on a currently defined user.

[#example-list-current-users]
==== Example: List Current Users

The following example lists the users currently defined on the cluster:

----
curl -v -X GET http://10.143.201.101:8091/settings/rbac/users \
-u Administrator:password | jq
----

If successful, the call returns `200 OK`, and an array such as the following:

----
[
  {
    "id": "testUser",
    "domain": "local",
    "roles": [
      {
        "role": "ro_admin",
        "origins": [
          {
            "type": "user"
          }
        ]
      }
    ],
    "groups": [],
    "external_groups": [],
    "name": "",
    "password_change_date": "2020-08-11T03:48:18.000Z"
  }
]
----

In this example, the object that is the sole member of the array contains values that specify the `domain`, the `role(s)`, the `groups`, the `external_groups`, the `name`, and the last `password_change_date` for a user who is currently the only one defined.

[#check-permissions]
=== Check Permissions

The REST API allows the permissions of the authenticating administrator to be confirmed, by means of the `POST` method and the `/pools/default/checkPermissions` URI.
The curl syntax is as follows:

----
curl -X POST
  http://<ip-address-or-domain-name>/pools/default/checkPermissions
  -u <username>:<password>
  -d <permissions-check-specification>
----

The `permissions-check-specification` must indicate whether the check is to be made at the level of the cluster (for permissions associated with global roles), or at the level of a bucket within the cluster (for permissions associated with bucket-specific roles); or at the level of a specific data-set associated with the buckets (such as `stats` or `views`); and must specify the permission (such as `read` or `write`) for which the check is to be made.
Cluster, bucket, and data-set, if specified, must be separated from one another with a period.
The permission to be checked for must be preceded by the `!` character.

A successful call returns `200 OK`, plus an object indicating whether the authenticating administrator's possession of the specified permission is `true` or `false`.

[#examples-check-permissions]
==== Examples: Check Permissions

The following example checks whether the authenticating administrator has `admin` permissions on the cluster (which is to say, the permission associated with the `cluster_admin` role):

----
curl -v -X POST http://10.143.201.101:8091/pools/default/checkPermissions \
-u gsanderson:gsanderson \
-d 'cluster!admin'
----

If the call is successful, and the authenticating administrator does has the specified permission, the following object is returned:

----
{"cluster!admin":true}
----

The following example checks whether the authenticating administrator has `read` permission on `stats` for the `travel-sample` bucket, and `write` permission on `travel-sample` data:

----
curl -v -X POST http://10.143.201.101:8091/pools/default/checkPermissions \
-u Administrator:password \
-d 'cluster.bucket[travel-sample].stats!read,cluster.bucket[travel-sample]!write' | jq
----

An object such as the following is returned:

----
{
  "cluster.bucket[travel-sample].stats!read": true,
  "cluster.bucket[travel-sample]!write": true
}
----







=== List Currently Defined Groups

To list currently defined user-groups, use the `GET` method with the `/settings/rbac/groups/`
URI.
The curl syntax is as follows:

----
curl -X GET -u <username:password>
  http://<ip-address-or-domain-name>:8091/settings/rbac/groups
----

If successful, the call returns `200 OK`, and an array each of whose members is an object containing information on one of the user-groups currently defined on the cluster.

==== Example: List Currently Defined Groups

The following example lists all user-groups currently defined on the cluster:

----
curl -v -X GET http://10.143.201.101:8091/settings/rbac/groups \
-u Administrator:password | jq
----

If successful, the call returns an array such as the following:

----
[
  {
    "id": "ClusterAdmins",
    "roles": [
      {
        "role": "cluster_admin"
      }
    ],
    "ldap_group_ref": "uid=cbadmins,ou=groups,dc=example,dc=com",
    "description": "Couchbase Server Cluster Administrators"
  },
  {
    "id": "RoAdmins",
    "roles": [
      {
        "role": "ro_admin"
      }
    ],
    "ldap_group_ref": "",
    "description": "Administrators with Read Only Admin role."
  },
  {
    "id": "XdcrAdmins",
    "roles": [],
    "ldap_group_ref": "",
    "description": "Administrators with the XDCR Admin role"
  }
]
----

Thus, the array contains three members, which respectively contain information on the `ClusterAdmins`, `RoAdmins`, and `XdcrAdmins` groups.
Note that the `ClusterAdmins` group is shown to have an `ldap_group_ref`: meaning that it corresponds to an LDAP group, defined on the LDAP server.
For information, see xref:learn:security/authentication-domains.adoc#native-ldap-support[Native LDAP Support].

[#create-users-and-groups]
== Create Users and Groups

The REST API allows users and groups to be created, and roles thereby assigned.
Curl syntax, parameter-descriptions, examples, and call-specific responses are described in the subsections below.
See xref:rest-api:rbac.adoc[General Responses], for further descriptions of error notifications.

Users can be either _local_ or _external_.
Groups can optionally be mapped to _external groups_, defined on an LDAP server.
For information, see xref:learn:security/authentication-domains.adoc[Authentication Domains].

[#create-a-local-user-and-assign-roles]
=== Create a Local User, and Assign Roles

To create a local user, use the `PUT` method with the `/settings/rbac/users/local/` URI.
The curl syntax is as follows:

----
curl -X PUT -u <username>:<password>
  http://<ip-address-or-domain-name>/settings/rbac/users/local/<new-username>
  -d password=<password>
  -d roles=[<role>]*
----

The specified `password` must conform to the settings established as described in xref:rest-api:rest-set-password-policy.adoc[Setting Password Policy].
If multiple instances of `role` are specified, these must be comma-separated.

If successful, the call returns `200 OK`.
No object is returned.

[#example-create-local-users]
==== Examples: Create Local Users

The following example creates a local user, assigning a single role.

----
curl -v -X PUT http://10.143.201.101:8091/settings/rbac/users/local/dgreen \
-u Administrator:password \
-d password=pwdpwd \
-d roles=ro_admin
----

This assigns user `dgreen` the `ro_admin` role.

Note that if multiple roles are to be assigned, these must be comma-separated.
If a role is to be limited to a specific bucket, the bucket-name must follow the name of the role, without a separator, enclosed in square-brackets.
This is demonstrated by the following example:

----
curl -v -X PUT http://10.143.201.101:8091/settings/rbac/users/local/rbrown
-u Administrator:password \
-d password=rbrownpassword \
-d roles=bucket_admin[travel-sample],bucket_admin[beer-sample]
----

Thus, the new user `rbrown` is assigned the `bucket_admin` role on the `travel-sample` bucket, and is assigned the same role on the `beer-sample` bucket.

The following example assigns one global role, and one bucket-specific:

----
curl -v -X PUT http://10.143.201.101/settings/rbac/users/local/krichards \
-u Administrator:password \
-d password=krpassword \
-d roles=cluster_admin,bucket_admin[travel-sample]
----

Thus, the new user `krichards` is assigned the `cluster_admin` role (this being a global role), and the `bucket_admin` role for the `travel-sample` bucket only.
