= Creating and Editing Buckets
:page-topic-type: reference

[abstract]
Buckets are created and edited with the `POST /pools/default/buckets` HTTP method and URI.

== HTTP Method and URI

----
POST /pools/default/buckets
----

[#description]
== Description

This creates a bucket.
The bucket can be of any available type: Couchbase, Ephemeral, or Memcached.
A name for the bucket, unique across the cluster, must be specified.
Names cannot be longer than 100 bytes (which is to say, characters).

A maximum of 30 buckets can be created on a single cluster.

[#curl-syntax]
== Curl Syntax

Note that all floats and integers in the following are _positive_ only.

----
curl -X POST -u <administrator>:<password>
  http://<ip-address-or-hostname>:<port>/pools/default/buckets
  -d name=<bucketName>
  -d bucketType=[ couchbase | ephemeral | memcached ]
  -d ramQuotaMB=<integer>
  -d evictionPolicy=[
          [ valueOnly | full ] |
          [ noEviction | nruEviction ]
        ]
  -d durabilityMinLevel=[
          [ none | majority | majorityAndPersistActive | persistToMajority ] |
          [ none | majority ]
        ]
  -d threadsNumber=[ 3 | 8 ]
  -d replicaNumber=[ 1 | 2 | 3 ]
  -d compressionMode=[ off | passive | active ]
  -d maxTTL=<integer>
  -d replicaIndex=[ 0 | 1 ]
  -d conflictResolutionType=[ seqno | lww ]
  -d autoCompactionDefined=[ true | false ]
  -d parallelDBAndViewCompaction=[ true | false ]
  -d databaseFragmentationThreshold[percentage]=<integer>
  -d databaseFragmentationThreshold[size]=<integer>
  -d viewFragmentationThreshold[percentage]=<integer>
  -d viewFragmentationThreshold[size]=<integer>
  -d indexCompactionMode=[ circular | append ]
  -d purgeInterval=[ <float> | <integer> ]
  -d allowedTimePeriod[abortOutside]=true
  -d allowedTimePeriod[toMinute]=<integer>
  -d allowedTimePeriod[toHour]=<integer>
  -d allowedTimePeriod[fromMinute]=<integer>
  -d allowedTimePeriod[fromHour]=<integer>
  -d ramQuotaMB=<integer>
  -d flushEnabled=[ 0 | 1 ]
----

The parameters are as follows:

* `name`.
A name for the bucket.
The name must be unique among the bucket-names defined for the cluster, and cannot be longer than 100 characters.
Acceptable characters are `A-Z`, `a-z`, and `0-9`.
Additionally, the _underscore_, _period_, _dash_, and _percent_ characters can be used.
+
A name _must_ be specified.
If no name or an improperly designed name is specified, a JSON document is returned, notifying of the error.
For example: : `{"name":"Bucket name needs to be specified"}`.

* `bucketType`.
The _type_ of the bucket, which can be `couchbase` (which is the default), `ephemeral`, or `memcached`.
For a detailed explanation of bucket types, see xref:learn:buckets-memory-and-storage/buckets.adoc[Buckets].
+
If an invalid bucket type is specified, an error occurs; and the notification `{"bucketType":"invalid bucket type"}` is returned.

* `ramQuota`.
The amount of memory to be allocated to the bucket, per node, in megabytes.
The minimum amount is 100 MB.
The maximum amount is the total Data Service memory quota configured per node, minus the amount already assigned to other buckets.
For information on per node memory configuration, see the page for xref:manage:manage-settings/general-settings.adoc[General] Settings.
+
A value for `ramQuota` _must_ be specified.
An incorrect memory-specification returns a notification such as `{"ramQuotaMB":"RAM quota cannot be less than 100 MB"}`.

* `evictionPolicy`.
The _ejection policy_ to be assigned to and used by the bucket.
(Note that _eviction_ is, in the current release, referred to as _ejection_; and this revised naming will continue in future releases.)
Policy-assignment depends on bucket type.
For a _Couchbase_ bucket, the policy can be `valueOnly` (which is the default) or `full`.
For an _Ephemeral_ bucket, the policy can be `noEviction` (which is the default) or `nruEviction`.
No policy can be assigned to a _Memcached_ bucket.
+
Incorrect specification of an ejection policy returns an error-notification, such as `{"evictionPolicy":"Eviction policy must be either 'valueOnly' or 'fullEviction' for couchbase buckets"}`
+
For information on ejection policies, see xref:learn:buckets-memory-and-storage/buckets.adoc#bucket-types[Bucket Types].
For general information on memory management in the context of ejection, see xref:learn:buckets-memory-and-storage/memory.adoc#ejection[Ejection].

* `durabilityMinLevel`.
A _durability level_ to be assigned to the bucket, as the minimum level at which all writes to the bucket must occur.
Level-assignment depends on bucket type.
For a _Couchbase_ bucket, the level can be `none`, `majority`, `majorityAndPersistActive`, or `persistToMajority`.
For an _Ephemeral_ bucket, the level can be `none` or `majority`.
No level can be assigned to a _Memcached_ bucket.
+
For information on durability and levels, see xref:learn:data/durability.adoc[Durability].

* `threadsNumber`.
The _priority_ for the bucket, as described in xref:manage:manage-buckets/create-bucket.adoc#bucket-priority[Create a Bucket].
Priority can be established as either _Low_ or _High_.
To establish priority as _Low_ (which is the default), the value of `threadsNumber` must be `3`.
To establish priority as _High_, the value must be `8`.
If any other value is used, the value is ignored; and the bucket's priority remains low.

* `replicaNumber`.
The number of _replicas_ for the bucket.
For information on replicas and replication, see xref:learn:clusters-and-availability/intra-cluster-replication.adoc[Intra-Cluster Replication] and xref:learn:buckets-memory-and-storage/vBuckets.adoc[vBuckets].
The possible values are `1` (which is the default), `2`, and `3`.
+
If more replicas are requested that can be assigned to the cluster, due to an insufficiency of nodes, no notification is returned. Instead, the maximum possible number of replicas is created: additional replicas will be added subsequently, if more nodes become available.

* `autoCompactionDefined`.
Whether the default _auto-compaction_ settings are to be modified for this bucket.
The value specified can be either `true` or `false` (which is the default).

.Create bucket parameters
[cols="100,237"]
|===
| Payload Arguments | Description

| `authType`
| Required parameter.
Type of authorization to be enabled for the new bucket as a string.
Defaults to blank password if not specified.
"sasl" enables authentication.
"none" disables authentication.

| `bucketType`
| Required parameter.
Type of bucket to be created.
String value.
"memcached" configures as Memcached bucket.
"couchbase" configures as Couchbase bucket.
This cannot be changed for a pre-existing bucket.

| `conflictResolutionType`
| Optional parameter.
String value '[.in]``lww``' (conflict resolution based on _timestamp_) or '[.in]``seqno``' (conflict resolution based on _sequence number_).
This parameter defaults to '[.code]``seqno``' if unspecified.
This cannot be changed once a bucket has been created.

| `evictionPolicy`
a|
Optional parameter, a string.
Possible values are `fullEviction` and `valueOnly`.
The default is `valueOnly`.
This parameter determines what is ejected: only the value or the key, value, and all metadata.

IMPORTANT: If you change the ejection policy of a pre-existing bucket then it will be restarted, resulting in temporary inaccessibility of data while the bucket warms up.

| `flushEnabled`
| Optional parameter.
Enables the ‘flush all’ functionality on the specified bucket.
Boolean.
1 enables flush all support, 0 disables flush all support.
Defaults to 0.

| `name`
| Required parameter.
Name for new bucket.
This cannot be changed for a pre-existing bucket.
A bucket name can only contain characters in the ranges of A-Z, a-z, and 0-9; with the addition of the underscore, period, dash and percent characters; and can be no more than 100 characters in length.

| `parallelDBAndViewCompaction`
| Optional parameter.
String value.
Indicates whether database and view files on disk can be compacted simultaneously.
Defaults to "false."

| `proxyPort`
| Required parameter.
Numeric.
Proxy port on which the bucket communicates.
Must be a valid network port which is not already in use.
You must provide a valid port number if the authorization type is not SASL.

| `ramQuotaMB`
| Required parameter.
RAM Quota for new bucket in MB.
Numeric.
The minimum you can specify is 100, and the maximum can only be as great as the memory quota established for the node.
If other buckets are associated with a node, RAM Quota can only be as large as the amount memory remaining for the node, accounting for the other bucket memory quota.

| `replicaIndex`
| Optional parameter.
Boolean.
1 enable replica indexes for replica bucket data while 0 disables.
Default of 1.
This cannot be changed for a pre-existing bucket.

| `replicaNumber`
| Optional parameter.
Numeric.
Number of replicas to be configured for this bucket.
Required parameter when creating a Couchbase bucket.
Default 1, minimum 0, maximum 3.

| `saslPassword`
| Optional Parameter.
String.
Password for SASL authentication.
Required if SASL authentication has been enabled.

| `threadsNumber`
a|
Optional Parameter.
Integer from 2 to 8.
Change the number of concurrent readers and writers for the data bucket.

IMPORTANT: If you change this setting for a pre-existing bucket then it will be restarted, resulting in temporary inaccessibility of data while the bucket warms up.

| `maxTTL`
| Optional Parameter.
Specifies the maximum TTL (time-to-live) for all documents in bucket in seconds.
If enabled and a document is mutated with no TTL or a TTL greater than than the maximum, its TTL will be set to the maximum TTL.
Setting this option to 0 disables the use of maxTTL, and the largest TTL that is allowed is 2147483647.
This option is only available for Couchbase and Ephemeral buckets in Couchbase Enterprise Edition.

| `compressionMode`
| Optional Parameter.
Specifies the compression-mode of the bucket.
There are three options; off, passive and active.
All three modes are backwards compatible with older SDKs, where Couchbase Server will automatically uncompress documents for clients that do not understand the compression being used.
This option is only available for Couchbase and Ephemeral buckets in Couchbase Enterprise Edition.

`Off`: Couchbase Server will only compress document values when persisting to disk.
This is suitable for use cases where compression could have a negative impact on performance.
Please note it is expected that compression in most use cases will improve performance.

`Passive`: Documents which were compressed by a client, or read compressed from disk will be stored compress in-memory.
Couchbase Server will make no additional attempt to compress documents that are not already compressed.

`Active`: Couchbase Server will actively and aggressively attempt to compress documents, even if they have not been received in a compressed format.
This provides the benefits of compression even when the SDK clients are not complicit.
|===

When creating a bucket, the `authType` parameter must be provided:

* If `authType` is set to `none`, then a proxyPort number must be specified.
* If `authType` is set to `sasl`, then the `saslPassword` parameter may optionally be specified.

The `ramQuotaMB` parameter specifies how much memory, in megabytes, is allocate to each node for the bucket.
The minimum supported value is 100MB.

* If the items stored in a memcached bucket take space beyond the `ramQuotaMB`, Couchbase Sever typically evicts items on a least-requested-item basis.
Couchbase Server might evict other infrequently used items depending on object size or on whether or not an item is being referenced.
* In the case of Couchbase buckets, the system might return temporary failures if the `ramQuotaMB` is reached.
The system tries to keep 25% of the available ramQuotaMB free for new items by ejecting old items from occupying memory.
In the event these items are later requested, they are retrieved from disk.

== Syntax

Curl request syntax:

[source,bourne]
----
curl -X POST -u [admin]:[password]  http://[ip_address]:8091/pools/default/buckets
  -d name=[new-bucket-name] -d ramQuotaMB=[value] -d authType=[none | sasl]
  -d replicaNumber=[value]
  -d proxyPort=[proxy-port]
----

== Example

Curl request example:

[source,bourne]
----
curl -X POST -u Administrator:password http://127.0.0.1:8091/pools/default/buckets \
-d name=newBucket -d ramQuotaMB=100 -d authType=none \
-d replicaNumber=2 \
-d proxyPort=11215
----

Curl request example to set conflict resolution type.
Set the parameter [.param]`conflictResolutionType` to `lww` during bucket creation.
For example, use the following command to create a bucket on the source cluster:

[source,bourne]
----
curl -X POST -u Administrator:asdasd http://<ip_address>:8091/pools/default/buckets
-d name=newBucketSource -d conflictResolutionType=lww
-d authType=sasl -d ramQuotaMB=4096
-d saslPassword=passw0rd -d bucketType=couchbase
----

Use the following command to create a bucket on the destination cluster:

[source,bourne]
----
curl -X POST -u Administrator:asdasd http://<ip_address>:8091/pools/default/buckets
-d name=newBucketDestination -d conflictResolutionType=lww
-d authType=sasl -d ramQuotaMB=4096
-d saslPassword=passw0rd -d bucketType=couchbase
----

Curl request to set maximum Bucket Time-To-Live, and to establish a compression mode:

[source,bourne]
----
curl -X POST -u Administrator:password http://127.0.0.1:8091/pools/default/buckets \
-d name=myTestBucket -d ramQuotaMB=100 \
-d bucketType=couchbase -d maxTTL=20000 \
-d compressionMode=Passive
----

Curl request to edit an existing bucket:

[source,bourne]
----
curl -X POST -u Administrator:password http://10.142.180.101:8091/pools/default/buckets/testBucket \
-d bucketType=couchbase \
-d autoCompactionDefined=false \
-d evictionPolicy=valueOnly \
-d threadsNumber=3 \
-d replicaNumber=1 \
-d compressionMode=passive \
-d maxTTL=20000 \
-d replicaIndex=0 \
-d ramQuotaMB=100 \
-d flushEnabled=0
----

Raw HTTP request example:

The parameters for configuring the bucket are provided as payload data.
Each parameter and value are provided as a key/value pair where each pair is separated by an ampersand.
Include the parameters setting in the payload of the HTTP `POST` request.

[source,bourne]
----
POST /pools/default/buckets
HTTP/1.1
Host: 10.5.2.54:8091
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Authorization: Basic YWRtaW46YWRtaW4=
Content-Length: xx
name=newbucket&ramQuotaMB=20&authType=none&replicaNumber=2&proxyPort=11215
----

== Response

If the bucket creation was successful, HTTP response 202 (Accepted) is returned with empty content.

----
202 Accepted
----

== Response codes

If the bucket could not be created, because the parameter was missing or incorrect, HTTP response 400 returns, with a JSON payload containing the error reason.

.Create bucket error codes
[cols="1,4"]
|===
| Error codes | Description

| 202
| Accepted

| 400
a|
Bad Request JSON with errors in the form of `{"errors": {….
}}`.
Possible error messages include:

* name: Bucket with given name already exists
* ramQuotaMB: RAM Quota is too large or too small
* replicaNumber: Must be specified and must be a non-negative integer
* proxyPort: port is invalid, port is already in use

| 404
| Object Not Found
|===
